
name: Quantum Cube CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Code Linting
        run: npm run lint
        
      - name: Unit Tests
        run: npm run test
        env:
          API_KEY: ${{ secrets.GEMINI_API_KEY }}

  build-and-deploy:
    name: Build and Deployment Strategy
    needs: validate
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Production Build
        run: npm run build
        
      - name: Deployment Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-assets
          path: dist/

      # Placeholder for automated deployment to host (e.g., GitHub Pages, Vercel, or Netlify)
      # - name: Deploy to Hosting
      #   run: echo "Deploying to production environment..."
